### ISSUE TITLE
部分角色的角色语音设置不生效

### ISSUE THREAD

**Issue by Koi4** [HIllya51/MashiroiroSymphony#1]
使用汉化补丁后，发现在Dialog设置中部分角色的语音音量及单独语音开关不生效，调整音量并不会使游戏中的角色对应语音音量产生变化

目前发现不生效的角色有樱乃和安洁，隼太的语音设置是生效的

移除补丁后设置可正常生效

**Comment by HIllya51** [comment]
已修正
